name: CI
on: [push]
jobs:
  build-and-deploy:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Test 🔧
        run: |
          npm install
          npm run lint
          npm run test

      - name: Coveralls 💉
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          path-to-lcov: ./test/unit/coverage/lcov.info

      - name: Build 🙅‍♀️
        run: |
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
